export const SEED_CARS = [
  {
    make: "Hyundai",
    model: "Creta 1.5 SX(O) Diesel AT",
    year: 2022,
    price: 1680000,
    mileageKm: 34200,
    fuelType: "Diesel",
    transmission: "Automatic",
    ownership: "1st Owner",
    bodyType: "SUV",
    color: "Polar White",
    registrationCity: "Mumbai (MH-02)",
    insuranceValidTill: "November 2026 (Comprehensive)",
    description: "Mint condition Hyundai Creta top-variant SX(O) Automatic in pristine Polar White. Single-owner driven with authorized showroom service history. Equipped with panoramic sunroof, ventilated front seats, Bose premium audio, and certified zero-accident status with clean chassis inspection report.",
    features: JSON.stringify([
      "Panoramic Sunroof",
      "Ventilated Front Seats",
      "10.25\" Bose 8-Speaker Audio",
      "Wireless Smartphone Charger",
      "Traction Control & Drive Modes",
      "Electronic Parking Brake with Auto Hold",
      "6 Airbags & ESP",
      "Diamond Cut Alloy Wheels"
    ]),
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&w=1200&q=80"
    ]),
    status: "AVAILABLE",
    isFeatured: true,
  },
  {
    make: "BMW",
    model: "3 Series 330i M Sport",
    year: 2021,
    price: 3850000,
    mileageKm: 26400,
    fuelType: "Petrol",
    transmission: "Automatic",
    ownership: "1st Owner",
    bodyType: "Sedan",
    color: "Portimao Blue",
    registrationCity: "Delhi (DL-1C)",
    insuranceValidTill: "January 2027 (Zero Dep)",
    description: "Immaculate BMW 330i M Sport with twin-turbocharged 258 BHP engine. Serviced exclusively at official BMW dealership with full service records available. Boasts M Aerodynamics pack, 18-inch M alloys, Harman Kardon audio system, and pristine Dakota leather interior.",
    features: JSON.stringify([
      "M Sport Aerodynamics Package",
      "Harman Kardon Surround Sound",
      "BMW Live Cockpit Professional",
      "Electric Glass Sunroof",
      "Ambient Interior Mood Lighting",
      "Paddle Shifters with Launch Control",
      "3-Zone Automatic Climate Control",
      "Apple CarPlay & Android Auto"
    ]),
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1553440569-bcc63803a83d?auto=format&fit=crop&w=1200&q=80"
    ]),
    status: "AVAILABLE",
    isFeatured: true,
  },
  {
    make: "Tata",
    model: "Nexon EV Max XZ+ Lux",
    year: 2023,
    price: 1390000,
    mileageKm: 19800,
    fuelType: "Electric",
    transmission: "Automatic",
    ownership: "1st Owner",
    bodyType: "SUV",
    color: "Pristine White",
    registrationCity: "Pune (MH-12)",
    insuranceValidTill: "March 2027 (Comprehensive)",
    description: "Next-generation long-range Electric SUV with 40.5 kWh battery pack (ARAI 437 km range). Complete battery health certification verified at 99.2%. Includes 7.2 kW home fast charger, ventilated leatherette seats, multi-mode regenerative braking, and 8-year battery warranty intact.",
    features: JSON.stringify([
      "40.5 kWh High-Density Battery",
      "Multi-Mode Regen Braking",
      "Ventilated Leatherette Seats",
      "Air Purifier with AQI Display",
      "Wireless Charger & Smart Keys",
      "Harmon 8-Speaker Audio System",
      "Electronic Stability Program (ESP)",
      "Rear View Camera with Guidelines"
    ]),
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=1200&q=80"
    ]),
    status: "AVAILABLE",
    isFeatured: true,
  },
  {
    make: "Honda",
    model: "City 1.5 ZX CVT (5th Gen)",
    year: 2021,
    price: 1075000,
    mileageKm: 42000,
    fuelType: "Petrol",
    transmission: "Automatic",
    ownership: "1st Owner",
    bodyType: "Sedan",
    color: "Golden Brown Metallic",
    registrationCity: "Bangalore (KA-03)",
    insuranceValidTill: "August 2026 (Comprehensive)",
    description: "The benchmark of luxury and reliability. Fully-loaded Honda City ZX CVT with smooth i-VTEC petrol engine, LaneWatch camera, electric sunroof, Alexa car connect, and pristine single-hand ownership. Complete dealer maintenance with new Michelin tyres fitted.",
    features: JSON.stringify([
      "One-Touch Electric Sunroof",
      "Honda LaneWatch Blind Spot Camera",
      "Full LED Headlamps with 9 Array In-line LEDs",
      "8\" Touchscreen with Apple CarPlay",
      "Walk-Away Auto Lock & Push Start",
      "6 Airbags (Front, Side, Curtain)",
      "Cruise Control & Paddle Shifts",
      "Perforated Leather Upholstery"
    ]),
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1590362891991-f776e747a588?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1517524008697-84bbe3c3fd98?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80"
    ]),
    status: "AVAILABLE",
    isFeatured: true,
  },
  {
    make: "Toyota",
    model: "Innova Crysta 2.4 ZX 7-Str AT",
    year: 2022,
    price: 2250000,
    mileageKm: 48000,
    fuelType: "Diesel",
    transmission: "Automatic",
    ownership: "1st Owner",
    bodyType: "SUV",
    color: "Super White",
    registrationCity: "Thane (MH-04)",
    insuranceValidTill: "December 2026",
    description: "Unmatched reliability and luxury touring comfort. Toyota Innova Crysta ZX 7-Seater Automatic with plush middle-row captain seats, touch infotainment, 7 airbags, and renowned D-4D diesel engine that runs like new. 100% genuine showroom records.",
    features: JSON.stringify([
      "Second-Row Luxury Captain Seats",
      "Automatic Climate Control with Rear Vents",
      "7 Airbags & Vehicle Stability Control",
      "Push Button Start with Smart Key",
      "Touchscreen Infotainment with Nav",
      "Cruise Control & Eco/Power Drive Modes",
      "Premium Hazel Brown Leather Seats",
      "Ambient Roof Illumination"
    ]),
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&w=1200&q=80"
    ]),
    status: "RESERVED",
    isFeatured: false,
  },
  {
    make: "Mahindra",
    model: "Thar LX 4x4 Hard Top AT",
    year: 2021,
    price: 1490000,
    mileageKm: 31500,
    fuelType: "Diesel",
    transmission: "Automatic",
    ownership: "1st Owner",
    bodyType: "SUV",
    color: "Napoli Black",
    registrationCity: "Gurgaon (HR-26)",
    insuranceValidTill: "October 2026",
    description: "The ultimate lifestyle 4x4 off-roader. Mahindra Thar LX Diesel Automatic with factory hard top, shift-on-the-fly 4WD system, adventure telemetry, touch infotainment, and aggressive stance. Never driven in heavy off-road, strictly highway and city commuter.",
    features: JSON.stringify([
      "Shift-on-the-Fly 4x4 with Mechanical Diff Lock",
      "Factory Fitted Solid Hard Top",
      "18\" Deep-Dish Alloy Wheels with AT Tyres",
      "Touchscreen Infotainment with Off-Road Stats",
      "Roll Cage & Built-in Roll Over Mitigation",
      "Drizzle Resistant Roof-Mounted Speakers",
      "Tyre Pressure Monitoring System (TPMS)",
      "Cruise Control & Hill Descent Control"
    ]),
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1200&q=80"
    ]),
    status: "AVAILABLE",
    isFeatured: false,
  },
  {
    make: "Mercedes-Benz",
    model: "C-Class C200 Progressive",
    year: 2020,
    price: 3400000,
    mileageKm: 38000,
    fuelType: "Petrol",
    transmission: "Automatic",
    ownership: "2nd Owner",
    bodyType: "Sedan",
    color: "Obsidian Black",
    registrationCity: "Mumbai (MH-01)",
    insuranceValidTill: "February 2027",
    description: "Graceful elegance with German precision. Mercedes-Benz C200 Progressive in deep Obsidian Black. Features panoramic glass sunroof, 64-color ambient mood lighting, active brake assist, Burmester surround sound, and dual digital cockpit displays.",
    features: JSON.stringify([
      "Panoramic Sliding Glass Sunroof",
      "64-Color Ambient Mood Lighting",
      "Burmester 13-Speaker Surround System",
      "Active Brake Assist & Attention Assist",
      "Electric Memory Seats with Lumbar Support",
      "Multibeam LED Headlamps with Adaptive Highbeam",
      "Wireless Charging & Smartphone Integration",
      "Dynamic Select with Individual Driving Modes"
    ]),
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=1200&q=80"
    ]),
    status: "SOLD",
    isFeatured: false,
  },
  {
    make: "Maruti Suzuki",
    model: "Grand Vitara Alpha Hybrid",
    year: 2023,
    price: 1725000,
    mileageKm: 16500,
    fuelType: "Hybrid",
    transmission: "Automatic",
    ownership: "1st Owner",
    bodyType: "SUV",
    color: "Arctic White",
    registrationCity: "Ahmedabad (GJ-01)",
    insuranceValidTill: "May 2027",
    description: "Ultra-fuel-efficient Strong Hybrid SUV delivering up to 27.97 km/l. Features panoramic sunroof, 360-degree parking camera, head-up display, ventilated seats, and seamless EV-to-Petrol driving modes with zero emissions at low speeds.",
    features: JSON.stringify([
      "Intelligent Electric Hybrid Technology",
      "Panoramic Sliding Sunroof",
      "Head-Up Display (HUD)",
      "360-Degree Surround View Camera",
      "Ventilated Front Seats",
      "9\" SmartPlay Pro+ Touchscreen",
      "Wireless Apple CarPlay & Android Auto",
      "6 Airbags & Hill Hold Assist"
    ]),
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1517524008697-84bbe3c3fd98?auto=format&fit=crop&w=1200&q=80"
    ]),
    status: "AVAILABLE",
    isFeatured: false,
  }
];

export const SEED_INQUIRIES = [
  {
    customerName: "Rajesh Sharma",
    phone: "+91 98765 43210",
    email: "rajesh.sharma@example.com",
    inquiryType: "TEST_DRIVE",
    preferredDate: "2026-09-14",
    preferredTime: "11:00 AM",
    message: "Interested in test driving the Creta SX(O) Automatic at your Mumbai showroom.",
    status: "NEW",
  },
  {
    customerName: "Vikram Malhotra",
    phone: "+91 98111 22334",
    email: "vikram.m@example.com",
    inquiryType: "RESERVE_BOOKING",
    preferredDate: "2026-09-15",
    tokenAmount: 10000,
    message: "Placing advance booking hold for the BMW 330i M Sport. Please confirm paperwork requirements.",
    status: "CONTACTED",
  },
  {
    customerName: "Ananya Deshmukh",
    phone: "+91 97654 11223",
    email: "ananya.d@example.com",
    inquiryType: "TEST_DRIVE",
    preferredDate: "2026-09-13",
    preferredTime: "4:30 PM",
    message: "Would like to check the Tata Nexon EV Max battery health and take a weekend trial.",
    status: "NEW",
  }
];

export const SEED_DEALERS = [
  {
    name: "Gagan Gowda (Super Admin)",
    phone: "9876543210",
    passwordRaw: "Admin@1234",
    role: "ADMIN",
    isActive: true,
  },
  {
    name: "Brothers Central Hub (Andheri)",
    phone: "9820011223",
    passwordRaw: "Dealer@123",
    role: "DEALER",
    isActive: true,
  },
  {
    name: "Apex Motors (Bandra West)",
    phone: "9820022334",
    passwordRaw: "Dealer@123",
    role: "DEALER",
    isActive: true,
  },
  {
    name: "Prestige Wheels (South Mumbai)",
    phone: "9820033445",
    passwordRaw: "Dealer@123",
    role: "DEALER",
    isActive: true,
  },
  {
    name: "Royal Auto Plaza (Thane)",
    phone: "9820044556",
    passwordRaw: "Dealer@123",
    role: "DEALER",
    isActive: true,
  },
  {
    name: "Urban Drive Dealership (Navi Mumbai)",
    phone: "9820055667",
    passwordRaw: "Dealer@123",
    role: "DEALER",
    isActive: true,
  },
  {
    name: "Elite Pre-Owned Hub (Worli)",
    phone: "9820066778",
    passwordRaw: "Dealer@123",
    role: "DEALER",
    isActive: true,
  },
];

